### ISSUE TITLE
Exception when hovering <expand> tag or attributes

### ISSUE THREAD

**Issue by davelopez** [davelopez/galaxy-language-server#41]
The ``<expand>`` element for macros is not supported in the XSD schema, so when trying to get information from the schema, like documentation or attributes, an exception will raise.

We should handle this particular element differently from the rest of the elements.

**Comment by bgruening** [comment]
Should the expand element not be part of the XSD?

**Comment by davelopez** [comment]
Yes, I am afraid so, this was one of the main reasons to write a language server as John explained here https://github.com/galaxyproject/galaxy/issues/9778#issuecomment-630167658
